import { useRef, useState } from "react";
import SearchPanel from "./components/SearchPanel";
import RiskCard from "./components/RiskCard";
import RiskFactors from "./components/RiskFactors";
import Forecast from "./components/Forecast";
import Explanation from "./components/Explanation";
import { getAnalysis, searchLocations } from "./services/api";
import type { Analysis, Location } from "./types";

const value = (number: number | null, unit: string, digits = 0) => number === null ? "—" : `${number.toFixed(digits)}${unit}`;

function App() {
  const [query, setQuery] = useState(""); const [results, setResults] = useState<Location[]>([]); const [analysis, setAnalysis] = useState<Analysis | null>(null); const [loadingSearch, setLoadingSearch] = useState(false); const [loadingAnalysis, setLoadingAnalysis] = useState(false); const [locating, setLocating] = useState(false); const [error, setError] = useState<string | null>(null); const [searchMessage, setSearchMessage] = useState<string | null>(null); const searchRequest = useRef<AbortController | null>(null); const analysisRequest = useRef<AbortController | null>(null);
  const search = async () => { const trimmed = query.trim(); if (!trimmed) return; searchRequest.current?.abort(); const controller = new AbortController(); searchRequest.current = controller; setLoadingSearch(true); setError(null); setSearchMessage(null); try { const locations = await searchLocations(trimmed, controller.signal); if (searchRequest.current !== controller) return; setResults(locations); if (!locations.length) setSearchMessage("No matching locations found. Try a city or place name."); } catch (err) { if ((err as DOMException).name !== "AbortError") setError(err instanceof Error ? err.message : "Location search failed."); } finally { if (searchRequest.current === controller) setLoadingSearch(false); } };
  const select = async (location: Location) => { analysisRequest.current?.abort(); const controller = new AbortController(); analysisRequest.current = controller; setResults([]); setLoadingAnalysis(true); setError(null); try { const result = await getAnalysis(location, controller.signal); if (analysisRequest.current === controller) setAnalysis(result); } catch (err) { if ((err as DOMException).name !== "AbortError") setError(err instanceof Error ? err.message : "Weather analysis failed. Please try again."); } finally { if (analysisRequest.current === controller) setLoadingAnalysis(false); } };
  const useMyLocation = () => { if (!navigator.geolocation) { setError("Location services are unavailable in this browser. Search for a city instead."); return; } setError(null); setLocating(true); navigator.geolocation.getCurrentPosition(position => { setLocating(false); void select({ id: null, name: "Current location", country: null, admin1: null, latitude: position.coords.latitude, longitude: position.coords.longitude, timezone: null }); }, geoError => { setLocating(false); const message = geoError.code === geoError.PERMISSION_DENIED ? "Location permission was denied. Search for a city instead." : geoError.code === geoError.TIMEOUT ? "Getting your location timed out. Please try again or search for a city." : "Your location could not be determined. Search for a city instead."; setError(message); }, { enableHighAccuracy: false, timeout: 10_000, maximumAge: 300_000 }); };
  return <main><header><div className="brand-mark">WR</div><div><h1>WeatherRisk <em>AI</em></h1><p>Real-time rainfall risk intelligence</p></div><span className="public-badge">Public decision support</span></header><div className="container"><SearchPanel query={query} results={results} loading={loadingSearch} locating={locating} error={error} onQueryChange={setQuery} onSearch={search} onSelect={select} onUseMyLocation={useMyLocation} />{searchMessage && <p className="notice" role="status">{searchMessage}</p>}{loadingAnalysis && <section className="loading-card" aria-live="polite"><div className="spinner" /> Building a verified weather analysis…</section>}{!analysis && !loadingAnalysis && <section className="empty-state"><p className="eyebrow">Start an analysis</p><h2>Search for a location or use your current location.</h2><p>The dashboard combines live forecast data, a significant-rainfall model, and deterministic risk assessment.</p></section>}{analysis && <Dashboard analysis={analysis} retry={() => select(analysis.weather.location)} />}</div></main>;
}

function Dashboard({ analysis, retry }: { analysis: Analysis; retry: () => void }) { const weather = analysis.weather; const location = weather.location; const retrievedAt = new Intl.DateTimeFormat(undefined, { dateStyle: "medium", timeStyle: "short", timeZone: weather.timezone }).format(new Date(weather.retrieved_at)); return <><section className="location-bar"><div><p className="eyebrow">Selected location</p><h2>{analysis.location_name ?? location.name}</h2><p>{location.country ?? "Current location"}</p></div><button className="text-button" onClick={retry}>Refresh analysis</button></section><div className="dashboard-grid"><section className="panel current"><div className="section-heading"><div><p className="eyebrow">Current conditions</p><h2>{weather.current.time ? "At latest provider update" : "Current weather"}</h2></div></div><div className="metric-grid"><Metric label="Temperature" value={value(weather.current.temperature_c, "°C")} /><Metric label="Humidity" value={value(weather.current.relative_humidity_percent, "%")} /><Metric label="Wind" value={value(weather.current.wind_speed_kmh, " km/h")} /><Metric label="Cloud cover" value={value(weather.current.cloud_cover_percent, "%")} /><Metric label="Recent 24h rain" value={value(weather.rainfall.recent_24h_mm, " mm", 1)} /><Metric label="Forecast 24h rain" value={value(weather.rainfall.forecast_next_24h_mm, " mm", 1)} /></div></section><RiskCard analysis={analysis} /></div><RiskFactors analysis={analysis} /><Explanation analysis={analysis} /><Forecast hours={weather.hourly_forecast} timezone={weather.timezone} expectedRainfall={weather.rainfall.forecast_next_24h_mm} /><section className="panel data-info"><div><p className="eyebrow">Data information</p><h2>Provenance & freshness</h2></div><div className="data-grid"><span><i className={`status-dot ${weather.freshness.status}`} />{weather.freshness.status === "fresh" ? "Fresh data" : "Stale data"} · {Math.round(weather.freshness.age_minutes)} min old</span><span>Source: {weather.provider.name}</span><span>Timezone: {weather.timezone}</span><span>Retrieved: {retrievedAt}</span><span>Target: {analysis.ml_prediction.target}</span></div></section></>; }
function Metric({ label, value }: { label: string; value: string }) { return <div className="metric"><span>{label}</span><b>{value}</b></div>; }
export default App;
