import { useRef, useState } from "react";
import ProductHero from "./components/ProductHero";
import SearchPanel from "./components/SearchPanel";
import RiskCard from "./components/RiskCard";
import RiskFactors from "./components/RiskFactors";
import Forecast from "./components/Forecast";
import Explanation from "./components/Explanation";
import Provenance from "./components/Provenance";
import { getAnalysis, reverseLocation, searchLocations } from "./services/api";
import type { Analysis, Location, ReverseLocation } from "./types";

function App() {
  const [query, setQuery] = useState(""); const [results, setResults] = useState<Location[]>([]); const [analysis, setAnalysis] = useState<Analysis | null>(null); const [selectedLocation, setSelectedLocation] = useState<Location | null>(null); const [deviceLocation, setDeviceLocation] = useState<ReverseLocation | null>(null); const [loadingSearch, setLoadingSearch] = useState(false); const [loadingAnalysis, setLoadingAnalysis] = useState(false); const [locating, setLocating] = useState(false); const [error, setError] = useState<string | null>(null); const [searchMessage, setSearchMessage] = useState<string | null>(null); const searchRequest = useRef<AbortController | null>(null); const analysisRequest = useRef<AbortController | null>(null); const locationIdentityRequest = useRef(0);
  const search = async () => { const trimmed = query.trim(); if (!trimmed) return; searchRequest.current?.abort(); const controller = new AbortController(); searchRequest.current = controller; setLoadingSearch(true); setError(null); setSearchMessage(null); try { const locations = await searchLocations(trimmed, controller.signal); if (searchRequest.current !== controller) return; setResults(locations); if (!locations.length) setSearchMessage("No matching locations found. Try a city or place name."); } catch (err) { if ((err as DOMException).name !== "AbortError") setError("Unable to search locations right now. Please try again."); } finally { if (searchRequest.current === controller) setLoadingSearch(false); } };
  const select = async (location: Location, currentDeviceLocation: ReverseLocation | null = null, preserveLocationRequest = false) => { if (!preserveLocationRequest) { locationIdentityRequest.current += 1; setSelectedLocation(location); } analysisRequest.current?.abort(); const controller = new AbortController(); analysisRequest.current = controller; setResults([]); setLoadingAnalysis(true); setError(null); if (!preserveLocationRequest || currentDeviceLocation) setDeviceLocation(currentDeviceLocation); try { const result = await getAnalysis(location, controller.signal); if (analysisRequest.current === controller) setAnalysis(result); } catch (err) { if ((err as DOMException).name !== "AbortError") setError("Unable to analyze this location. We couldn't retrieve the latest weather data."); } finally { if (analysisRequest.current === controller) setLoadingAnalysis(false); } };
  const useMyLocation = () => { if (!navigator.geolocation) { setError("Location services are unavailable in this browser. Search for a city instead."); return; } const requestId = locationIdentityRequest.current + 1; locationIdentityRequest.current = requestId; setSelectedLocation(null); setError(null); setLocating(true); navigator.geolocation.getCurrentPosition(position => { const latitude = position.coords.latitude; const longitude = position.coords.longitude; const location: Location = { id: null, name: "Current location", country: null, admin1: null, latitude, longitude, timezone: null }; setLocating(false); void select(location, null, true); void reverseLocation(latitude, longitude).then(identity => { if (locationIdentityRequest.current !== requestId) return; setDeviceLocation(identity); }).catch(() => { /* Analysis continues with the coordinate fallback. */ }); }, geoError => { setLocating(false); setError(geoError.code === geoError.PERMISSION_DENIED ? "Location permission was denied. Search for a city instead." : geoError.code === geoError.TIMEOUT ? "Getting your location timed out. Please try again or search for a city instead." : "Your location could not be determined. Search for a city instead."); }, { enableHighAccuracy: false, timeout: 10_000, maximumAge: 300_000 }); };
  return <main className="app-shell"><ProductHero analysis={analysis} selectedLocation={selectedLocation} deviceLocation={deviceLocation}><SearchPanel query={query} results={results} loading={loadingSearch} locating={locating} error={error} onQueryChange={setQuery} onSearch={search} onSelect={location => void select(location)} onUseMyLocation={useMyLocation} /></ProductHero><div className="dashboard-shell">{searchMessage && <p className="notice" role="status">{searchMessage}</p>}{loadingAnalysis && <LoadingState />}{error && analysis && <section className="error-card" role="alert"><div><p className="eyebrow">Analysis unavailable</p><h2>Unable to analyze this location</h2><p>{error}</p></div><button onClick={() => void select(analysis.weather.location, deviceLocation)}>Try again</button></section>}{!analysis && !loadingAnalysis && <section className="empty-state"><span className="empty-radar" aria-hidden="true" /><p className="eyebrow">Environmental intelligence</p><h2>Choose a location to begin.</h2><p>Search for a city or use your current location to generate a live rainfall-risk assessment.</p></section>}{analysis && <Dashboard analysis={analysis} />}</div></main>;
}

function LoadingState() { return <section className="loading-card" aria-live="polite"><div className="spinner" /><div><p className="eyebrow">Analyzing location</p><h2>Building your rainfall outlook</h2><p>Retrieving current weather · calculating risk assessment · assembling evidence</p></div></section>; }
function Dashboard({ analysis }: { analysis: Analysis }) { return <><div className="forecast-first"><span className="forecast-anchor">Rainfall forecast</span><Forecast hours={analysis.weather.hourly_forecast} timezone={analysis.weather.timezone} expectedRainfall={analysis.weather.rainfall.forecast_next_24h_mm} /></div><div className="analysis-top"><RiskCard analysis={analysis} /><RiskFactors analysis={analysis} /></div><div className="analysis-detail"><Explanation analysis={analysis} /><Provenance analysis={analysis} /></div></>; }
export default App;
