import { useState } from "react";
import SearchPanel from "./components/SearchPanel";
import RiskCard from "./components/RiskCard";
import Forecast from "./components/Forecast";
import Explanation from "./components/Explanation";
import { getAnalysis, searchLocations } from "./services/api";
import type { Analysis, Location } from "./types";

const value = (number: number | null, unit: string, digits = 0) => number === null ? "—" : `${number.toFixed(digits)}${unit}`;
function App() { const [query, setQuery] = useState(""); const [results, setResults] = useState<Location[]>([]); const [analysis, setAnalysis] = useState<Analysis | null>(null); const [loadingSearch, setLoadingSearch] = useState(false); const [loadingAnalysis, setLoadingAnalysis] = useState(false); const [error, setError] = useState<string | null>(null); const [searchMessage, setSearchMessage] = useState<string | null>(null);
  const search = async () => { const trimmed = query.trim(); if (!trimmed) return; setLoadingSearch(true); setError(null); setSearchMessage(null); try { const locations = await searchLocations(trimmed); setResults(locations); if (!locations.length) setSearchMessage("No matching locations found. Try a city or place name."); } catch (err) { setError(err instanceof Error ? err.message : "Location search failed."); } finally { setLoadingSearch(false); } };
  const select = async (location: Location) => { setResults([]); setLoadingAnalysis(true); setError(null); try { setAnalysis(await getAnalysis(location)); } catch (err) { setError(err instanceof Error ? err.message : "Weather analysis failed."); } finally { setLoadingAnalysis(false); } };
  return <main><header><div className="brand-mark">WR</div><div><h1>WeatherRisk <em>AI</em></h1><p>Real-time rainfall risk intelligence</p></div><span className="public-badge">Public decision support</span></header><div className="container"><SearchPanel query={query} results={results} loading={loadingSearch} error={error} onQueryChange={setQuery} onSearch={search} onSelect={select} />{searchMessage && <p className="notice">{searchMessage}</p>}{loadingAnalysis && <section className="loading-card" aria-live="polite"><div className="spinner" /> Loading verified weather analysis…</section>}{!analysis && !loadingAnalysis && <section className="empty-state"><p className="eyebrow">Start an analysis</p><h2>Search for a location to assess its next 24 hours.</h2><p>The dashboard combines real-time forecast data, a significant-rainfall model, and deterministic risk assessment.</p></section>}{analysis && <Dashboard analysis={analysis} retry={() => select(analysis.weather.location)} />}</div></main>; }
function Dashboard({ analysis, retry }: { analysis: Analysis; retry: () => void }) { const weather = analysis.weather; const location = weather.location; return <><section className="location-bar"><div><p className="eyebrow">Selected location</p><h2>{analysis.location_name ?? location.name}</h2><p>{location.country ?? ""} · {location.latitude.toFixed(3)}° N, {location.longitude.toFixed(3)}° E</p></div><button className="text-button" onClick={retry}>Refresh analysis</button></section><div className="dashboard-grid"><section className="panel current"><div className="section-heading"><div><p className="eyebrow">Current conditions</p><h2>{weather.current.time ? "At latest provider update" : "Current weather"}</h2></div></div><div className="metric-grid"><Metric label="Temperature" value={value(weather.current.temperature_c, "°C")} /><Metric label="Humidity" value={value(weather.current.relative_humidity_percent, "%")} /><Metric label="Wind" value={value(weather.current.wind_speed_kmh, " km/h")} /><Metric label="Cloud cover" value={value(weather.current.cloud_cover_percent, "%")} /><Metric label="Recent 24h rain" value={value(weather.rainfall.recent_24h_mm, " mm", 1)} /><Metric label="Forecast 24h rain" value={value(weather.rainfall.forecast_next_24h_mm, " mm", 1)} /></div></section><RiskCard analysis={analysis} /></div><Explanation analysis={analysis} /><Forecast hours={weather.hourly_forecast} /><section className="panel data-info"><div><p className="eyebrow">Data information</p><h2>Provenance & freshness</h2></div><div className="data-grid"><span><i className={`status-dot ${analysis.status}`} />{analysis.status === "fresh" ? "Fresh data" : "Stale data"}</span><span>Source: {weather.provider.name}</span><span>Timezone: {weather.timezone}</span><span>Retrieved: {new Intl.DateTimeFormat(undefined, { dateStyle: "medium", timeStyle: "short" }).format(new Date(weather.retrieved_at))}</span></div></section></>; }
function Metric({ label, value }: { label: string; value: string }) { return <div className="metric"><span>{label}</span><b>{value}</b></div>; }
export default App;
